flowchart LR

    %% Актори
    actor[Користувач]
    admin[Адміністратор]

    %% Система та варіанти використання
    subgraph Онлайн_Магазин
        uc1([Увійти])
        uc2([Переглянути товар])
        uc3([Оформити замовлення])
        uc4([Переглянути статус])
        uc5([Керувати товарами])
        uc6([Перевірити наявність])
    end

    %% Зв'язки асоціації
    Користувач --> uc1
    Користувач --> uc2
    Користувач --> uc3
    Користувач --> uc4

    Адміністратор --> uc5
    uc5 --> uc6 %% Асоціація між use case

    %% Зв'язки include/extend
    uc3 -. "<<include>>" .-> uc1
    uc3 -. "<<include>>" .-> uc6
    uc2 -. "<<extend>>" .-> uc3
    uc4 -. "<<extend>>" .-> uc1
