flowchart LR

    %% Актори
    user[Користувач]
    admin[Адміністратор]

    %% Система та варіанти використання
    subgraph Онлайн_Магазин
        uc1([Увійти])
        uc2([Переглянути товар])
        uc3([Оформити замовлення])
        uc4([Переглянути статус])
        uc5([Керувати товарами])
        uc6([Перевірити наявність])
    end

    %% Зв'язки асоціації
    user --> uc1
    user --> uc2
    user --> uc3
    user --> uc4

    admin --> uc5
    
    %% Асоціація між use case
    uc5 --> uc6

    %% Зв'язки include/extend
    uc3 -. "<<include>>" .-> uc1
    uc3 -. "<<include>>" .-> uc6
    uc2 -. "<<extend>>" .-> uc3
    uc4 -. "<<extend>>" .-> uc1
